ooni/sysadmin

ooni-sysadmin-ng/install-common.sh
ooni-sysadmin-ng/install-ooni-backend.sh
ooni-sysadmin-ng/oonibackend.conf.sh
ooni-sysadmin-ng/oonibackend.service.sh

`sudo sh install-ooni-backend.sh` on a fresh debian jessie ec2 instance gets `oonib` running as a service under systemd.
(some things i should polish, but i just tested it on a new instance and it works)

replace ansible with a very small shell script

---

ansible/roles/ooniprobe/tasks/main.yml

Fix check set_ooniprobe_pip is defined before checking if it is equal
to true. https://github.com/TheTorProject/ooni-sysadmin/issues/21
As spotted by @elationfoundation

Fix check set_ooniprobe_pip is defined before

---

ansible/roles/ooni-backend/tasks/main.yml

Check if set_supervisord is defined before checking if it is equal
to true. https://github.com/TheTorProject/ooni-sysadmin/issues/22
As spotted by @elationfoundation

Fix check if set_supervisord is defined

---

ansible/roles/ooniprobe/tasks/install-git.yml

Git install should better install from git master the latest ooniprobe
version that includes all pluggable transports tests and potential fixes

Install ooniprobe from git (master)

---

README.md
ansible/install-thirdparty.yml
ansible/roles/third-party/tasks/install-lantern.yml
ansible/roles/third-party/tasks/install-openvpn.yml
ansible/roles/third-party/tasks/install-psiphon.yml
ansible/roles/third-party/tasks/main.yml
ansible/roles/third-party/templates/psi_generate_dat.py.j2
ansible/roles/third-party/vars/main.yml

This ansible roles installs the third party
tools required for some ooniprobe tests.
* Add Lantern installation task
* Add Psiphon installation task
* Add OpenVPN installation task
* Add ansible role documentation

Ansible third party tools role

---

ansible/roles/common/tasks/tor.yml
ansible/roles/common/vars/main.yml

Fix to correct repo name taken from ansible variable.
Add tor-version for the experimental repo.
As spotted by @elationfoundation
https://github.com/TheTorProject/ooni-sysadmin/issues/23

Fix tor repo release name variables

---

ansible/roles/tor-pluggable-trans/tasks/install-obfsproxy.yml

obfsproxy package requires dependencies that have
been already installed via pip

Change installation of obfsproxy via pip

---

ansible/roles/common/tasks/main.yml

The playbook should install the the python-dev role and then run
conditionally the pip update otherwise it may just end up having the
version of pip overridden by the debian package one.
As spotted by @hellais

Change the order of executed roles in common

---

docker/backend/Dockerfile
docker/bouncer/Dockerfile
docker/probe/Dockerfile

Use Debian Jessie release to build the docker image.
Install ansible from apt packages since Debian Jessie release includes
an updated ansible package helping to reduce dependencies on the Docker
build file. Replace git package by git-core.

Change OS release to jessie, reduce dependencies

---

docker/backend/Dockerfile

This change disables running ooni-backend in supervisod in docker build
image.

Do not run backend in supervisord for docker image

---

ansible/roles/docker_py/tasks/main.yml
ansible/roles/ooni-backend/tasks/docker_deploy.yml

Ansible docker_py module has deprecated the build state and bumped the
docker-py dependency to >= 1.7.0. Adding latest to the version doesn't
work as expected as the docker_py is not correctly validating the
version number.
The module option 'build' in state is deprecated and will now behave the
same as the 'present' option.
Set the docker container policy to always, to restart stopped containers

Add docker-py version requirement, set state,restart policy

---

ansible/deploy-proteus-events.yml
ansible/roles/proteus-events/templates/proteus-events.toml.j2

1) As stated in TheTorProject/proteus#13, we must not set a topic
for Android because that leads to FCM rejecting the message.
2) Define two different topics for iOS, one for production and
one for testing, because I guess we'll need them soon.

fix,refactor(proteus-events): topics correctness

---

ansible/roles/alertmanager/templates/alertmanager.yml.j2

We have no transparent rule to configure email aliases, so it's better to be safe and use flattened list instead of admin@ in systems allowing explicit list of addresses.
I don't think that x4 increase of Amazon SES bill matters. That's still dozens of emails, not thousands.
CC: @bassosimone, @hellais, @anadahz

Use explicit list of alert recipients instead of team@ or admin@

---

ansible/dom0-bootstrap.yml
ansible/roles/eclipsis/tasks/main.yml
ansible/roles/gh/tasks/main.yml

I believe now the only one that is still broken is `bouncer.infra.ooni.nu`, yet this is a box we should phase out/deprecate anyways and `labs.ooni.io` where the certbot script is not working as expected (it's a testing machine so it's not essential).
* apparmor was actually only a problem on wiki.ooni.io, which I just disabled
* There was a certbot problem on hkgbouncer, which was due to some empty config file being left over from some bad upgrade or something (I just deleted it)
* datacollector had a broken ntp service, which I fixed by running updating the ntp client
The remaining alerts were just related to smartd being broken, which is now disabled as part of the playbook on all greenhost boxes.

Fix systemd alerts

---

scripts/docker-build

@hellais here is a (hopefully, handy) warning to avoid confusion while building images with `docker-build` script.

Warn on dirty git tree on `docker-build`

---

ansible/roles/ooni-explorer-next/defaults/main.yml
ansible/roles/ooni-explorer-next/tasks/main.yml
ansible/roles/ooni-explorer-next/templates/ngx-explorer

Modified `explorer-next`'s nginx configuration to mock API data from static files stored in `/var/www/explorer/data/`.

Serve static files as placeholder API data for explorer country pages

---

ansible/host_vars/prometheus.infra.ooni.io/vars.yml
ansible/roles/prometheus/templates/prometheus.yml.j2

Add http-pings to public OONI *.onion endpoints, see #239
Also, replace hard-coded IP addresses with resolve-DNS-on-template.
The logic behind that a bit unusual configuration is discussed in https://github.com/prometheus/blackbox_exporter/issues/264#issuecomment-442936583

Add http-pings to public OONI *.onion endpoints, see #239

---

ansible/deploy-ooni-explorer-next.yml
ansible/roles/letsencrypt/tasks/main.yml
ansible/roles/ooni-explorer-next/defaults/main.yml
ansible/roles/ooni-explorer-next/tasks/main.yml

I tried switching the API server address provided as an environment variable. Doesn't seem to be the right way. The country page which fetches data from the new endpoints on the API server seems to still hit the production API server (based on docker logs).

Use test API server for Explorer test instance

---

ansible/roles/prometheus/files/alert_rules.yml

* Stop alerting on low memory
* Drop the severity labels as it was leading to some alerts only being sent via email

Improve the alerting rules

---

docker/airflow/Dockerfile

I'm cleaning up various notes and found a note on `dumb-init`. Actually, it's no longer needed, it's possible to replace it with `tini` that is shipped with modern docker versions.
I'm leaving it as a comment instead of separate ticket as there is no _need_ to drop `dumb-init`, it's just some cleanup.

Add comment on built-in docker init

---

ansible/deploy-ooni-orchestrate.yml

So far I deployed 0.3.0 only on the testing infrastructure.
I think we should roll this out on the production endpoints too as it will increase testing coverage for people that have increased the maximum timeout and it has a small extra bandwidth cost.
The maximum response size will go up to 10x the current size, but it's still well under 100KB (77KB in the case of Iran which has a very big test list). Considering the fact that the web_connectivity test will likely consume much more bandwidth just to run the checks and do the upload I think it's reasonable to roll this out on production.
We may want to in the future to also do some smarter logic to impose a limit in the app by passing the `limit=` query parameter to the request.

Update orchestrate to 0.3.0

---

ansible/host_vars/prometheus.infra.ooni.io/vars.yml
ansible/inventory
ansible/templates/iptables.filter.part/amsexplorer.ooni.nu

Fixes the following alerts:
> [RESOLVED] amsexplorer.ooni.nu:9100 is not `up`
This was caused by not having added the host to the `have_fw` group (new VMs on eclipsis have a much more strict firewall by default and hosts need to be added to that group in order to write a rule as part of `dom0-bootstrap` to allow prometheus to scrape it)
> [FIRING] https://explorer.ooni.io/api/reports/countByCountry endpoint down
Was caused by legacy OONI Explorer having those endpoints available. Since we deployed the new explorer those endpoints don't exists anymore and it's not a good monitoring target anymore.

Fix amsexplorer

---

ansible/inventory

c.collector.ooni.io now points to the oonified probe services and since 24h no traffic is recorded towards this host, hence we are dropping it from the inventory and cleaning up the host.

Drop c.collector from the inventory

---

ansible/host_vars/mia-slack.ooni.nu/vars.yml

Default is a message max of 512 bytes on IRC, not sure if this bot does the right thing, but according to its docs that should be it: https://node-irc.readthedocs.io/en/latest/API.html#irc.Client

currently long lines are cut off on irc

---

ansible/roles/explorer/templates/ngx-explorer

This exposes the RSS feed from the fastpath on the explorer host

Explorer rss feed

---

ansible/roles/prometheus/files/alert_rules.yml

We separate the onion jobs from the non onion jobs and alert only when
the onion service is not reachable for at least 60 minutes.
This fixes: https://github.com/ooni/sysadmin/issues/400

Make the onion service alerts less noisy

---

ansible/roles/explorer/defaults/main.yml

Two consecutive releases were deployed. `2.0.9` was a bugfix.

Explorer release - 2.0.8, 2.0.9

---

ansible/deploy-explorer.yml
ansible/roles/explorer/tasks/main.yml

Aside from updating the docker container tag, I also made a small change to address a deprecation warning. The idea to get a bit more confident about handling ansible configurations.

Deploy explorer-test with ams-pg-test as API server

---

ansible/roles/probe-services/templates/tor_targets.json

The colocation site where the bridge is running will be shut down.

Remove default bridge 37.218.240.34.

---

ansible/roles/ooni-backend/templates/tor_targets.json
ansible/roles/probe-services/templates/tor_targets.json
scripts/make_tor_targets.py

Upon manual inspection I noticed that 2 things change (it's hard to see
in the diff because we weren't previously sorting keys):
1. The removal of the smallerRichard bridge as requested by @meskio in https://github.com/ooni/sysadmin/pull/493
2. The id of the bridge 51.222.13.177:80 changed from
fa69b2ee7a7c8975af2452ecd566f67a6459d397a4cefc30be86a670675cdc23 to
662218447d396b9d4f01b585457d267735601fedbeb9a19b86b942f238fe4e7b. The
new ID is correct and it's unclear how this ID was determined in the
original PR: https://github.com/ooni/sysadmin/pull/463.
The second point might create data analysis issues in the future, but I
don't really see a way around it except remembering about this
inconsistency so we can manually remap the in the future.

Tor targets

---

ansible/host_vars/monitoring.ooni.org/vars.yml
ansible/roles/prometheus/templates/prometheus.yml.j2

Alert if we screwed the pooch with haproxy and nginx hence we cannot access .well-know/acme-challenge anymore.
Based on a true story.
While there:
1. remove monitoring code for onion services that was removed on monitoring.ooni.org but was still in ansible
2. make sure ansible contains the hotfix for https://github.com/ooni/backend/issues/747

feat(monitoring): monitor .well-known/acme-challenge for ams-pg-test

---

ansible/roles/ooni-backend/templates/rotation_setup.sh

We're not using the private repository to publish the test helpers anymore and instead we should use the public repository.

fix(rotation): use the public repository

---

tools/debops-ci

Summary of changes:
* Ignore rebuilding of debian packages that have been deleted
* Add `--dry-run` CLI option to make it easier to locally test
As noted inside of https://github.com/ooni/backend/pull/798, debops-ci will attempt to build a package even when the package has been deleted.
This happens because it will rebuild any package that it detects by running:
```
git diff --name-only {commit}
```
and filtering by those names that match the string `debian/changelog`.
However, since it's not filtering by the status, which could also be that the `debian/changelog` had been deleted, it thinks it should rebuild also a deleted package.
In this patch I fix that, by ignoring any paths that have the `D` (deleted) status.
I also add support for a `--dry-run` command line flag, allowing you to …

Fix debops
