ooni/sysadmin

ansible/roles/ooni-backend/hosts, ansible/roles/ooni-backend/tasks/install.yml
Adds supports for installing ooni-backend outside a virtualenv instance.
Fixes pip dependency issues by installing the packages with the correct
order and removes some conflicting python system (apt) packages.
=> Add support for non virtualenv backend, fix dependencies

README.md
* Add M-Lab deployment URL
* OONI backend upgrade instructions notes
* Correct maintainer username
=> Add M-Lab deployment, upgrade infrastructure text

ansible/roles/ooni-backend/tasks/populate_bouncer_base.yml, ansible/roles/ooni-backend/vars/main.yml
=> Fix: point to the correct bouncer file

docs/psql_replication.md
WIP and not ready to be merged yet.
=> Add streaming PostgreSQL replication documentation

ansible/deploy-oonibackend-instances.yml, ansible/roles/ooni-backend/hosts, ansible/roles/ooni-backend/tasks/docker_deploy.yml, ansible/roles/ooni-backend/templates/Dockerfile.j2
* The oonibackend docker images should always rebuild and deployed upon
successful build.
* Fix playbook conditionals
=> Fix conditionals, docker image rebuild and deploy on success

ansible/roles/ooni-measurements/tasks/main.yml, ansible/roles/ooni-measurements/vars/main.yml
re: https://github.com/TheTorProject/ooni-measurements/issues/20
=> Add support to deploy a specific version of the repository

ansible/inventory-check.yml, ansible/roles/dom0-defaults/handlers/main.yml, ansible/roles/dom0-defaults/tasks/main.yml, ansible/roles/nginx-prometheus/handlers/main.yml, ansible/roles/nginx-prometheus/templates/nginx.conf
=> More dom0 fixes

.travis.yml, README.md, ansible/ansible-version.yml, ansible/deploy-pipeline.yml, ansible/ext-inventory.yml, ansible/inventory-check.yml, ansible/roles/airflow/files/docker-trampoline, ansible/roles/plpsql/handlers/main.yml, ansible/roles/plpsql/tasks/main.yml, ansible/roles/plpsql/templates/pg_hba.conf, ansible/roles/plpsql/templates/postgresql.conf, ansible/roles/prometheus/files/alert_rules.yml, scripts/verify-chameleon.sh
=> new ansible, postgres config and some fixes

ansible/roles/ooni-run/defaults/main.yml
This is currently deployed.
Will merge once CI passes.
=> Bump ooni-run to 0.1.4

ansible/inventory-check.yml, ansible/roles/ooni-run/defaults/main.yml
I am currently re-deploying it to check that it works. Will merge thereafter.
=> Update ooni-run path

ansible/roles/ooni-explorer/defaults/main.yml, ext/gh-droplets.json
Not yet deployed. Will do once the image is uploaded.
=> Bump explorer tag

ansible/host_vars/prometheus.infra.ooni.io/vars.yml, ansible/inventory, ansible/inventory-check.yml, ansible/roles/airflow/files/nodeexp_airflow, ansible/roles/airflow/tasks/main.yml, ansible/roles/blackbox_exporter/tasks/main.yml, ansible/roles/blackbox_exporter/templates/blackbox.yml.j2, ansible/roles/blackbox_exporter/templates/blackbox_exporter.service, ansible/roles/node_exporter/defaults/main.yml, ansible/roles/node_exporter/files/seeksample.py, ansible/roles/node_exporter/tasks/main.yml, ansible/roles/prometheus/files/alert_ooni.yml, ansible/roles/prometheus/files/alert_rules.yml
That's another a PR for an umbrella #226
=> More monitoring & alerting from 2018-epic

ansible/roles/ooni-explorer-next/defaults/main.yml
Deployed `explorer-next` via playbook `deploy-ooni-explorer-next.yml`
=> Test explorer-next deployment

README.md, ansible/host_vars/jupyter.ooni.io/vars.yml
Mention the required ansible version in Readme
=> Add sarath to jupyther host

ansible/roles/airflow/files/docker-trampoline
See: https://github.com/ooni/orchestra/pull/57 for details on the bug
=> Bump orchestra-scripts to a working version

README.md
I'm unsure whether we need to apply strict checks like we do for
ansible or we're just fine with suggesting pinning.
=> README.md: document that we need dnspython

ansible/roles/airflow/files/docker-trampoline
This deploys: https://github.com/ooni/pipeline/pull/144
=> Bump pipeline-shovel version

ansible/deploy-prometheus.yml, ansible/deploy-tor.yml, ansible/dom0-bootstrap.yml, ansible/group_vars/gh/vars.yml, ansible/host_vars/prometheus.infra.ooni.io/vars.yml, ansible/roles/dom0-defaults/tasks/main.yml, ansible/roles/etc-onion/defaults/main.yml, ansible/roles/etc-onion/files/ipv6-ula.zone, ansible/roles/etc-onion/files/resolv.conf, ansible/roles/etc-onion/handlers/main.yml, ansible/roles/etc-onion/tasks/coredns-bin.yml, ansible/roles/etc-onion/tasks/main.yml, ansible/roles/etc-onion/templates/Corefile, ansible/roles/etc-onion/templates/coredns.service, ansible/roles/etc-onion/templates/ipv6-ula-tor, ansible/roles/etc-onion/templates/torrc, ansible/roles/tor-bin/handlers/main.yml, ansible/roles/tor-bin/tasks/main.yml
That's infra part of _Monitoring public OONI `*.onion` endpoints_ for #239.
=> System-wide *.onion support for Prometheus VM

ansible/roles/airflow/files/docker-trampoline
xref: https://github.com/ooni/pipeline/pull/151
=> Bump the shovel

README.md, docker/postgres-metadb/Dockerfile, docker/postgres-metadb/metadb_s3_tarz, docs/metadb-sharing.md, scripts/metadb_s3_tarx
Backup script #272, some further actions are needed:
=> PostgreSQL `metadb` backup

ansible/roles/airflow/files/docker-trampoline, ansible/roles/ooni-measurements/vars/main.yml
https://github.com/ooni/pipeline/pull/198
=> Deploy pipeline-shovel 20190605-0a2af2d4

ansible/roles/airflow/files/airflow-dags/analysis.py, ansible/roles/airflow/files/docker-trampoline
=> Add analysis command to docker-trampoline and DAG

scripts/pipeline-reprocess
I also copied the file onto datacollector and created a file
`affected.bucket_date` with inside the following:
```
2019-07-04
2019-07-05
2019-07-06
2019-07-07
[.. snip ..]
2019-08-13
2019-08-14
2019-08-15
```
I will now proceed to run `make reprocess` from inside of a screen
session
=> This is needed to backfill confirmed on the msmts

ansible/play
Fix ansible's questionable humour
=> No more cows

ansible/roles/ooni-explorer-next/defaults/main.yml
=> Bump explorer tag for v2.0.3 release

ansible/roles/ooni-measurements/templates/ngx-oomsm-web
Global throttling - later we can add throttling for heavy API calls
=> Add API HTTP throttling

ansible/roles/node_exporter/handlers/main.yml, ansible/roles/node_exporter/tasks/main.yml, ansible/roles/node_exporter/templates/collector-metrics.service
Count report files into /run/nodeexp/collector_metrics
e.g. collector_reports_count 255
=> Add simple collector metrics to count reports

ansible/roles/airflow/files/docker-trampoline, ansible/roles/ooni-measurements/vars/main.yml
This is related to: https://github.com/ooni/pipeline/issues/273
=> Publish ooni data private

ansible/host_vars/prometheus.infra.ooni.io/vars.yml, ansible/roles/prometheus/templates/prometheus.yml.j2, ansible/roles/pushgateway/templates/pushgateway_nginx.conf
Fixes: https://github.com/ooni/sysadmin/issues/415
=> Drop brie host from monitoring

ansible/roles/prometheus/templates/prometheus.service
implements: https://github.com/ooni/sysadmin/issues/402
=> Bump prometheus retention time to 30 days

ansible/roles/explorer/defaults/main.yml
Deployed successfully. Merging.
=> Deploy explorer@2.0.5

ansible/roles/explorer/defaults/main.yml
=> Deploy explorer@2.0.6

ansible/roles/probe-services/templates/tor_targets.json
The bridge exposes a port over both IPv4 and IPv6.
=> Add latest default obfs4 bridge.

ansible/roles/explorer/defaults/main.yml
=> Deploy explorer@2.0.7

ansible/roles/dom0-defaults/tasks/main.yml
bash-completion, file, iotop, man-db
helps with #433
=> dom0: add utilities

ansible/roles/ooni-measurements/handlers/main.yml, ansible/roles/ooni-measurements/tasks/main.yml, ansible/roles/ooni-measurements/templates/ngx-oomsm-web
=> Improve API caching

ansible/roles/probe-services/templates/tor_targets.json
See also: <https://bugs.torproject.org/33630>
=> Remove noisebridge01 default bridge.

ansible/deploy-explorer.yml, ansible/roles/explorer/defaults/main.yml
was already deployed a few days ago
=> Explorer release/2.0.9

ansible/deploy-explorer.yml
Deploy the changes to explorer test instance for it to work with the new API at ams-pg.ooni.org
=> New api explorer test

ansible/roles/explorer/defaults/main.yml
Contains the hotfix for the `AS0` issue ooni/explorer#495
=> Deploy explorer@2.0.10

ansible/deploy-explorer.yml
=> Deploy explorer-test@2.1.0-rc.2

ansible/deploy-explorer.yml, ansible/roles/explorer/defaults/main.yml
Releasing OONI Explorer v2.1.0 as part of the API flip
=> Release Explorer 2.1.0

ansible/deploy-explorer.yml, ansible/roles/explorer/defaults/main.yml
Applies fix for ooni/explorer#500
=> Deploy explorer@2.1.1

ansible/deploy-explorer.yml, ansible/roles/explorer/defaults/main.yml
=> Explorer hotfix for search since date default

ansible/roles/explorer/defaults/main.yml
This was merged a little while ago.
=> Deploy explorer@2.1.3

ansible/deploy-explorer.yml, ansible/roles/explorer/defaults/main.yml
This was deployed a while ago.
=> Deploy explorer v2.4.4

ansible/roles/explorer/defaults/main.yml
contains commit that deploys `v2.5.0`
=> Deploy explorer v2.5.1

ansible/roles/probe-services/templates/tor_targets.json
Louis-Philippe Véronneau generously set up this bridge for us.  David
Goulet mentions that this bridge runs in the same autonomous system (and
data centre) as his default bridge.
=> Add new default obfs4 bridge.

ansible/roles/ooni-run/tasks/main.yml
=> OONI Run 0.4.0

ansible/roles/explorer/defaults/main.yml
=> OONI Explorer 2.9.0

ansible/roles/explorer/defaults/main.yml
- deploy explorer
- deploy explorer
=> Deploy explorer

ansible/deploy-vpsprobes.yml, ansible/group_vars/all/vars.yml, ansible/inventory, ansible/poetry.lock, ansible/pyproject.toml, ansible/roles/base-bullseye/tasks/main.yml, ansible/roles/vpsprobes/meta/main.yml, ansible/roles/vpsprobes/tasks/main.yml, ansible/setup_ansible_prereqs.sh
* Add ansible requirements setup
=> Add more probes to vpsprobes deployment

ansible/group_vars/all/vars.yml
This adds my public key to the admin users list.
=> Add ssh pub key to adm_logins

ansible/deploy-monitoring.yml
See: https://github.com/ooni/devops/pull/32
=> Disable deploy-monitoring

ansible/roles/base-bookworm/templates/resolved.conf
=> Change wikimedia DNS with quad9
